Document: hdbc-sqlite3
Title: Debian hdbc-sqlite3 Manual
Author: <insert document author here>
Abstract: This manual describes what hdbc-sqlite3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hdbc-sqlite3/hdbc-sqlite3.sgml.gz

Format: postscript
Files: /usr/share/doc/hdbc-sqlite3/hdbc-sqlite3.ps.gz

Format: text
Files: /usr/share/doc/hdbc-sqlite3/hdbc-sqlite3.text.gz

Format: HTML
Index: /usr/share/doc/hdbc-sqlite3/html/index.html
Files: /usr/share/doc/hdbc-sqlite3/html/*.html

  
